### ISSUE TITLE
Come hai imparato il meccanismo dell'app per l'auth e le varie cose? 

### ISSUE THREAD

**Issue by itstermoh** [DTrombett/portaleargo-api#259]

**Comment by DTrombett** [comment]
Sono partito da un vecchio issue (ReLoia/ArgoScuolaNext-NodeJS#1) dove degli utenti già avevano provato ad ispezionare le richieste fatte dall'app per eseguire il login ma senza riuscire a completare l'operazione. Così ho provato anch'io e sono riuscito ad eseguire correttamente l'autenticazione e ad accedere ai dati del profilo. Poi ispezionando le richieste sono anche riuscito a capire come ottenere gli altri dati
